config/routes.rb
Rails.application.routes.draw do

  root to: "questions#index"

  resources :questions do
    resources :answers
  end

  devise_for :users

  devise_scope :user do 
    get "/users/sign_out" => "devise/sessions#destroy"
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  default_scope { order(created_at: :asc) }
  belongs_to :question
  belongs_to :user

  validates :body, presence: true
  validates :question, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :answers
  has_many :questions


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :load_question, only: [:new, :create, :update, :destroy]
  before_action :load_answer, only: [:edit, :update, :destroy]

  def new
    @answer = Answer.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    if @answer.update(answer_params)
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to question_path(@question)
  end


  private 

  def load_answer
    @answer = Answer.find (params[:id])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:title, :body, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :load_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answers = @question.answers
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end


  private

  def load_question
    @question = Question.find (params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, answer_attributes: [:answer, :body, :question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/create.js.erb
$('.answers').append('<%= j render partial: 'questions/answer', object: @answer %>');
$('#answer_body').val('');

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Traininginius
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %p.notice= notice
    %p.alert= alert

    .container
      .nav
        .navbar
          .container
            - if current_user
              = current_user.email
              = link_to "sign_out",  destroy_user_session_path
              = link_to 'Ask question', new_question_path
            - else
              = link_to "sign_in", new_user_session_path
              = link_to "sign up",  new_user_registration_path
            =link_to 'All questions', questions_path

    = yield

app/views/questions/_answer.html.haml
%p= answer.body
-if user_signed_in? && answer.user_id == current_user.id
  = button_to "delete the answer", question_answer_path(@question, answer), id: "delete_answer_#{ answer.id }", method: :delete

app/views/questions/_answers.html.haml
- @question.answers.each do |answer|
  .answer
    = render partial: "answer", locals: {answer: answer }

app/views/questions/index.html.haml
!!!
%html

%head

%body

  %div
    - @questions.each do |q|
      %p=  link_to q.title, question_path(q)

app/views/questions/new.html.haml
!!!
%html

  %head
    %title ask question

  %body

    %p Ask your question
    %div
      = simple_form_for @question do |f|
        = f.input :title, placeholder: 'title'
        = f.input :body, placeholder: 'ask a question'
        = f.button :submit

app/views/questions/show.html.haml
%div
  %h2= @question.title
  %h2= @question.body
  - if user_signed_in? && @question.user_id == current_user.id
    = button_to "delete the question", @question, :method=>:delete, :class=>:destroy

  .answers
    = render 'answers'


%div.create_answer
  -if user_signed_in?
    = simple_form_for [@question, @answer], remote: true do |f|
      = f.input :body
      = f.button :submit
  -else
    %p= 'login or register to write a response'